name: joljak
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  kakao_map_plugin: ^0.3.7
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  image_picker: ^1.2.0
  exif: ^3.3.0
  http_parser: ^4.0.2
  dio: ^5.9.0
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  path: ^1.9.1
  image: ^4.2.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
